# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - ruby-full
    - build-essential
    - zlib1g-dev
  jobs:
   pre_install:
      - gem install jekyll bundler --user-install
      - cd docs && $HOME/.gem/ruby/3.0/bin/bundle install
      - cd docs && $HOME/.gem/ruby/3.0/bin/bundle exec jekyll build --destination ../_readthedocs/html
