# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  commands:
    - asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    - asdf install ruby 3.1.2
    - asdf global ruby 3.1.2
    - gem install bundler
    - bundle config set --local deployment 'true'
    - bundle config set --local without development
    - bundle install
    - >
      JEKYLL_ENV=production bundle exec jekyll build --destination
      _readthedocs/html --baseurl $(echo -n "$READTHEDOCS_CANONICAL_URL" | cut
      -d '/' -f 4-)
