# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  commands:
    - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409b6b1796c275462a1703113804bb82d39dc0e3 7d2baf1cf37b13e2069d6956105bd0e739499bdb && curl -sSL https://get.rvm.io | bash -s stable
    - ~/.rvm/bin/rvm autolibs disable && ~/.rvm/bin/rvm install ruby 3.1.2
    - PATH="$HOME/.rvm/rubies/ruby-3.1.2/bin:$PATH" gem install bundler
    - PATH="$HOME/.rvm/rubies/ruby-3.1.2/bin:$PATH" bundle install
    - PATH="$HOME/.rvm/rubies/ruby-3.1.2/bin:$PATH" bundle exec jekyll build --destination _readthedocs/html --baseurl $(echo -n "$READTHEDOCS_CANONICAL_URL" | cut -d '/' -f 4-)
