name: sp-repo-review
description: "Runs sp-repo-review"
branding:
  icon: package
  color: blue
inputs:
  package-dir:
    description: "Path to Python package, if different from repo root"
    required: false
    default: ""
  select:
    description: "Checks to select, overrides pyproject.toml"
    required: false
    default: ""
  ignore:
    description: "Checks to ignore, overrides pyproject.toml"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      id: python
      with:
        python-version: "3.13"
        update-environment: false

    # prettier-ignore
    - name: Run repo-review
      shell: bash
      run: >
        pipx run
        --python '${{ steps.python.outputs.python-path }}'
        --spec '${{ github.action_path }}[cli]'
        repo-review .
        --format html
        --stderr rich
        --select "${{ inputs.select }}"
        --ignore "${{ inputs.ignore }}"
        --package-dir "${{ inputs.package-dir }}"
        >> $GITHUB_STEP_SUMMARY
