[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
{%- if cookiecutter.project_type == "pybind11" %}
    "pybind11>=2.9.0",
{%- elif cookiecutter.project_type == "skbuild" %}
    "scikit-build>=0.14",
{%- endif %}
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/{{ cookiecutter.project_name.replace('-', '_') }}/_version.py"


[tool.cibuildwheel]
test-extras = ["test"]
test-command = "pytest {project}/tests"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "INFO"
testpaths = [
    "tests",
]


[tool.mypy]
files = "src"
python_version = "3.7"
warn_unused_configs = true
strict = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true


[tool.check-manifest]
ignore = [
    ".github/**",
    "docs/**",
    ".pre-commit-config.yaml",
    ".readthedocs.yml",
    "src/*/_version.py",
    "noxfile.py",
]

[tool.isort]
profile = "black"


[tool.pylint]
master.py-version = "3.7"
master.ignore-paths= ["src/{{ cookiecutter.project_name.replace("-", "_") }}/_version.py"]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.disable = [
  "design",
  "fixme",
  "line-too-long",
  "wrong-import-position",
]
