name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  change-detection:
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/reusable-change-detection.yml

  cookie:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cookie)
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-cookie.yml

  rr-tests:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-rr)
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-rr-tests.yml

  docs:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-docs)
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-docs.yml

  pass:
    if: always()
    needs:
      - change-detection
      - cookie
      - rr-tests
      - docs
    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: >-
            ${{
              !fromJSON(needs.change-detection.outputs.run-cookie)
              && '
              cookie,
              '
              || ''
            }} ${{
              !fromJSON(needs.change-detection.outputs.run-rr)
              && '
              rr-tests,
              '
              || ''
            }} ${{
              !fromJSON(needs.change-detection.outputs.run-docs)
              && '
              docs,
              '
              || ''
            }}
          jobs: ${{ toJSON(needs) }}
