name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0

  change-detection:
    permissions:
      contents: read
      pull-requests: read
    uses: $/.github/workflows/reusable-change-detection.yml

  cookie:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cookie)
    permissions:
      contents: read
    uses: $/.github/workflows/reusable-cookie.yml

  rr-tests:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-rr)
    permissions:
      contents: read
    uses: $/.github/workflows/reusable-rr-tests.yml

  docs:
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-docs)
    permissions:
      contents: read
    uses: $/.github/workflows/reusable-docs.yml

  pass:
    if: always()
    needs:
      - lint
      - change-detection
      - cookie
      - rr-tests
      - docs
    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          allowed-skips: >-
            ${{
              !fromJSON(needs.change-detection.outputs.run-cookie)
              && '
              cookie,
              '
              || ''
            }} ${{
              !fromJSON(needs.change-detection.outputs.run-rr)
              && '
              rr-tests,
              '
              || ''
            }} ${{
              !fromJSON(needs.change-detection.outputs.run-docs)
              && '
              docs,
              '
              || ''
            }}
          jobs: ${{ toJSON(needs) }}
